In [1]:
import pandas as pd
import numpy as np

In [13]:
# print sys.argv
# if len(sys.argv) > 1:
#     csv = sys.argv[1]
# else:
csv = "data/rank1.csv"
csv2 = "data/find1.csv"

rank = pd.read_csv(csv, index_col=False)
find = pd.read_csv(csv2, index_col=False)
rank.sort_values('trial')

,rank_id,hit_id,assignment_id,worker_id,time,rank0,rank1,rank2,rank3,rank4,rank5,rank6,rank7,rank8,rank9,trial,gen
0,1,3VZYA8PITNXBI6P8RQU696IQDP850Q,3RRCEFRB7MBXTUMB13DMDF3FFZH4B0,A1ZD8RU6YB0VEU,2017-12-02 21:55:56+00,17,9,8,7,9999,24,18,12,30,-9999,0,0
20,21,3I7SHAD35LVN8OAY4OW15N3Z7Y8M71,3EF8EXOTT1UMJEN42D71D5FPBLRJ10,A2UJ2GHCZO7B14,2017-12-03 01:58:26+00,44,57,9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0,1
19,20,3I7SHAD35LVN8OAY4OW15N3Z7Y8M71,3VZLGYJEYL9K9UD1RSVUW87GZYJXZR,A1NDM9R54FJMPW,2017-12-03 01:57:59+00,44,57,9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0,1
15,16,3I7SHAD35LVN8OAY4OW15N3Z7Y8M71,3NPI0JQDAO4JE92BZ9WVG7KWC3OPTF,A1ABFCIB4W3I39,2017-12-03 01:52:44+00,9999,57,44,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0,1
13,14,38EHZ67RILR61HLZXR0VB0GS61OGMV,3T111IHZ5EPL679CEVV3U2JZJE0R90,A24B2ZZJ04FNDN,2017-12-02 23:07:59+00,9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0,1
10,11,3VZYA8PITNXBI6P8RQU696IQDP850Q,3ATPCQ38J8988RV3KW1XYTNGSIVYAK,A30V1UH00MWJU5,2017-12-02 22:34:18+00,30,18,24,17,8,9999,12,9,7,-9999,0,0
7,8,3VZYA8PITNXBI6P8RQU696IQDP850Q,3TDXMTX3CBTLVP4VQ1YIW0R66G7I68,A36TQOAAAR7M9L,2017-12-02 22:03:41+00,17,18,7,8,9,12,9999,30,24,-9999,0,0
14,15,3UZUVSO3P6U8H3P8RWA7BXVGTL9MEK,3I02618YA05YEMH0ZEM5L36YVHMPUX,A24B2ZZJ04FNDN,2017-12-02 23:08:25+00,9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,0,1
18,19,3J06WJ78HMJ891530E08YX2FK9RVVJ,3S96KQ6I9M3APCZLU050GD37YKLTD5,ANN162CY5IAGN,2017-12-03 01:57:50+00,50,49,40,9999,-9999,-9999,-9999,-9999,-9999,-9999,1,1
9,10,3VGET1QSZZYJD04C8Q2OEL5Q50I7W9,3NJM2BJS4W52SS00DN15RXKSOGDPCJ,A1LDYRTFF28GR,2017-12-02 22:21:47+00,9999,31,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,0
5,6,3VGET1QSZZYJD04C8Q2OEL5Q50I7W9,3LEIZ60CDJYU8YV3OCPGG5LYSUH9Z7,A36TQOAAAR7M9L,2017-12-02 21:59:54+00,9999,31,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,0
11,12,3VGET1QSZZYJD04C8Q2OEL5Q50I7W9,36WLNQG78Z9FLWJ4Q9PZM1F6SOCEBH,AVHJ2SNIMGZ91,2017-12-02 22:41:57+00,9999,31,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,0
4,5,3VGET1QSZZYJD04C8Q2OEL5Q50I7W9,3IKZ72A5B4F9SJ8XOAEEVE00LE3NFV,A3T71W88062DB7,2017-12-02 21:58:40+00,9999,31,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,0
25,26,3J06WJ78HMJ891530E08YX2FK9RVVJ,31JLPPHS2UTWUSSG5UDP9UB88ZGO3H,A3FW9NWR6TJ4M9,2017-12-03 02:19:04+00,50,49,40,9999,-9999,-9999,-9999,-9999,-9999,-9999,1,1
3,4,3VGET1QSZZYJD04C8Q2OEL5Q50I7W9,3R6BYFZZP7BE4DM1QG1NTGRYNSDXFP,A1ZD8RU6YB0VEU,2017-12-02 21:56:35+00,9999,31,-9999,-9999,-9999,-9999,-9999,-9999,-9999,-9999,1,0
16,17,3J06WJ78HMJ891530E08YX2FK9RVVJ,3U8YCDAGXPF3YC6Z1KNAW181KODQ0V,A1ABFCIB4W3I39,2017-12-03 01:54:18+00,9999,50,49,40,-9999,-9999,-9999,-9999,-9999,-9999,1,1
23,24,3J06WJ78HMJ891530E08YX2FK9RVVJ,3WZ36BJEV3FHAF11G4EULNF7VZABTH,A1HS8H18KJ6OJH,2017-12-03 02:07:35+00,50,49,40,9999,-9999,-9999,-9999,-9999,-9999,-9999,1,1
21,22,3J06WJ78HMJ891530E08YX2FK9RVVJ,3WMOAN2SRBWYOGUNOPJID03M993NVX,A1NDM9R54FJMPW,2017-12-03 01:58:50+00,50,40,9999,49,-9999,-9999,-9999,-9999,-9999,-9999,1,1
26,27,3JHB4BPSFJ8I7MWJBE120SEACPUQ95,3K3R2QNK8B2DMZ1TIPQ8ZD6JQDFU9I,A10VMEX3R3EML1,2017-12-03 02:43:26+00,54,48,9999,46,41,45,-9999,-9999,-9999,-9999,2,1
24,25,360ZO6N6J0IRM7YRJLULJJU52OWM9D,3WLEIWSYHOGXHTAAXH4U6B9FQZ2H2B,A1HS8H18KJ6OJH,2017-12-03 02:08:14+00,54,48,46,9999,41,45,-9999,-9999,-9999,-9999,2,1
22,23,360ZO6N6J0IRM7YRJLULJJU52OWM9D,3X1FV8S5JXQSEOD11L6NNGUP8XIGVJ,AG8PCITDPLLKU,2017-12-03 02:07:15+00,54,48,9999,46,45,41,-9999,-9999,-9999,-9999,2,1
8,9,30UZJB2POGB7ZYO5ADCPB4GXG1S53L,3PWWM24LHSX4OI9HUDAOTYGGNF0829,AK3DF1BXS8DSM,2017-12-02 22:04:00+00,34,29,26,25,22,21,20,19,9999,-9999,2,0
2,3,30UZJB2POGB7ZYO5ADCPB4GXG1S53L,3XLBSAQ9Z4BQUF7A9FRW29USX4SZ7K,A2P2T7K63H0C7F,2017-12-02 21:56:28+00,26,29,19,25,21,22,20,9999,34,-9999,2,0
6,7,30UZJB2POGB7ZYO5ADCPB4GXG1S53L,33IZTU6J810N8IRNW01M0FADCI7XS8,A36TQOAAAR7M9L,2017-12-02 22:01:18+00,25,21,9999,20,26,29,19,34,22,-9999,2,0
17,18,360ZO6N6J0IRM7YRJLULJJU52OWM9D,3LYA37P8IQMI7WBEMV02KWSBCMIKBJ,A1Z43R9TV8VNJL,2017-12-03 01:54:49+00,45,54,48,46,9999,41,-9999,-9999,-9999,-9999,2,1
27,28,3JHB4BPSFJ8I7MWJBE120SEACPUQ95,3MYYFCXHJ36TKBUMHP50EQUCVDN4GX,A33P1MWZTFI8RL,2017-12-03 02:49:46+00,48,9999,54,46,41,45,-9999,-9999,-9999,-9999,2,1
12,13,3HYV4299HZVTWEN4XV0O6FUL9GKE8O,3GGAI1SQEVXW7P3NL79DATQXJC4CME,A1OU2FW26L47VV,2017-12-02 23:06:44+00,21,22,26,29,34,25,20,19,9999,-9999,2,0
1,2,30UZJB2POGB7ZYO5ADCPB4GXG1S53L,3DBQWDE4Y6XHQMF8IY15929NWKPN5C,A1ZD8RU6YB0VEU,2017-12-02 21:56:27+00,21,9999,22,19,25,34,29,26,20,-9999,2,0
28,29,3JHB4BPSFJ8I7MWJBE120SEACPUQ95,3LUY3GC63ZZWGB54M6TUBBSEN607PO,A2R9T5TWU2RVAL,2017-12-03 02:52:38+00,54,48,46,45,41,9999,-9999,-9999,-9999,-9999,2,1

In [71]:
# The world's worst funciton
'''
for trial in results.trial.unique():
    trial_results = results[results.trial == trial]
    ids = []
    places = {}
    # Get unique ids
    for rank in range(10):
        # print trial_results['rank%i'%rank].head(n=1).values[0]
        ids.append(trial_results['rank%i'%rank].head(n=1).values[0])
    
    ids = list(set(ids))
    for id_ in ids:
        places[id_] = []
        
    for i, HIT in trial_results.iterrows():
        for rank in range(10):
            places[HIT['rank%i'%rank]].append(rank)
    
    sort = {}
    for id_ in places:
        if id_ != -9999:
            sort[id_] = np.mean(places[id_])
    
    print min(sort, key=sort.get)
'''

17
21
9999

In [14]:
ranks = ['rank%i' % i for i in range(10)]
crosstab = pd.melt(rank, ['rank_id', 'trial'], ranks)
crosstab.head()

   rank_id  trial variable  value
0        1      0    rank0     17
1        2      2    rank0     21
2        3      2    rank0     26
3        4      1    rank0   9999
4        5      1    rank0   9999

In [15]:
crosstab['rank'] = crosstab['variable'].apply(lambda x: ranks.index(x))
crosstab

     rank_id  trial variable  value  rank
0          1      0    rank0     17     0
1          2      2    rank0     21     0
2          3      2    rank0     26     0
3          4      1    rank0   9999     0
4          5      1    rank0   9999     0
5          6      1    rank0   9999     0
6          7      2    rank0     25     0
7          8      0    rank0     17     0
8          9      2    rank0     34     0
9         10      1    rank0   9999     0
10        11      0    rank0     30     0
11        12      1    rank0   9999     0
12        13      2    rank0     21     0
13        14      0    rank0   9999     0
14        15      0    rank0   9999     0
15        16      0    rank0   9999     0
16        17      1    rank0   9999     0
17        18      2    rank0     45     0
18        19      1    rank0     50     0
19        20      0    rank0     44     0
20        21      0    rank0     44     0
21        22      1    rank0     50     0
22        23      2    rank0     54     0
23        24      1    rank0     50     0
24        25      2    rank0     54     0
25        26      1    rank0     50     0
26        27      2    rank0     54     0
27        28      2    rank0     48     0
28        29      2    rank0     54     0
29         1      0    rank1      9     1
..       ...    ...      ...    ...   ...
260       29      2    rank8  -9999     8
261        1      0    rank9  -9999     9
262        2      2    rank9  -9999     9
263        3      2    rank9  -9999     9
264        4      1    rank9  -9999     9
265        5      1    rank9  -9999     9
266        6      1    rank9  -9999     9
267        7      2    rank9  -9999     9
268        8      0    rank9  -9999     9
269        9      2    rank9  -9999     9
270       10      1    rank9  -9999     9
271       11      0    rank9  -9999     9
272       12      1    rank9  -9999     9
273       13      2    rank9  -9999     9
274       14      0    rank9  -9999     9
275       15      0    rank9  -9999     9
276       16      0    rank9  -9999     9
277       17      1    rank9  -9999     9
278       18      2    rank9  -9999     9
279       19      1    rank9  -9999     9
280       20      0    rank9  -9999     9
281       21      0    rank9  -9999     9
282       22      1    rank9  -9999     9
283       23      2    rank9  -9999     9
284       24      1    rank9  -9999     9
285       25      2    rank9  -9999     9
286       26      1    rank9  -9999     9
287       27      2    rank9  -9999     9
288       28      2    rank9  -9999     9
289       29      2    rank9  -9999     9

[290 rows x 5 columns]

In [16]:
grouped = crosstab.groupby(['trial', 'value'])['rank'].mean()
grouped = grouped.reset_index()

for trial in grouped.trial.unique():
    print "\nBEST FOR TRIAL %i: " % trial,
    best_id = grouped[grouped.trial == trial].sort_values('rank')['value'].head(n=1).values[0]
    print best_id
    if best_id == 9999:
        print find[find.trial == trial].original.head(n=1).values[0]
    else:
        print find[find.find_id == best_id].updated.values[0]

BEST FOR TRIAL 0:  44
Brown tarp next to hotdog vendor.

BEST FOR TRIAL 1:  50
find the trash can next to the tree on the right side of the street

BEST FOR TRIAL 2:  54
Find the yellow sign with the animal depiction on the right side of the road.